name = input("Введите имя ")
sername = input("Введите Фамилию ")
otchestvo = input("Введите отчество ")
birthday = input("Введите дату рождения ")
address = input("Введите адрес ")
number = input("Введите номер участка ")
print("Пациент - ", sername, name, otchestvo, birthday, address, number)
